# Call this whatever you want
name: scraper

# When does it get run?
on:
  # workflow_dispatch means "I can click a button and force it to run"
  workflow_dispatch:
  # schedule/cron means "on a set schedule"
  schedule:
    - cron: '*/90 * * * *'
jobs:
  scrape:
    # For some reason, we run love versions of linux
    runs-on: ubuntu-latest
    steps:
      # Download all of the code from your repo
      - name: Check out this repo
        uses: actions/checkout@v3
      # Set up Python 3.11.2
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install necessary Python packages
        run: pip install pandas beautifulsoup4 requests
      # MAKE SURE YOUR SCRAPER FILENAME MATCHES THE FILENAME HERE!!
      - name: Run the scraping script
        run: python automatic-scraper/scraper.py
      # I just stole the rest of this code so don't ask me questions about it
      - name: Commit and push if content changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
